name: Build and Deploy
on:
  push:
    branches:
      - server

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Create environment file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
          envkey_PORT: ${{ secrets.PORT }}
          envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
          file_name: server/config/config.env

      - name: Set up gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Deploy App to App Engine
      - name: Publish app to Google App Engine
        run: |
          ls
          gcloud config set project saloni-shivdasani && gcloud app deploy
        working-directory: ./server
