name: Build and Host Admin
on:
  push:
    paths:
      - "admin/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
        working-directory: ./admin
      - name: Create environment file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_REACT_APP_ACCOUNT: ${{ secrets.REACT_APP_ACCOUNT }}
        envkey_REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
        envkey_REACT_APP_AUTH_CLIENT: ${{ secrets.REACT_APP_AUTH_CLIENT }}
        file_name: admin/.env
      - name: Build
        run: npm run build
        working-directory: ./admin
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: ./admin/build/
  host:
    name: Host
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: ./admin/build/
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project saloni-shivdasani-admin
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./admin
